### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by LuchiBobra7** [LuchiBobra7/next-jobs#24]
- [x] Fix header animation
- [x] Delete blurred images
- [x] Delete companies link
- [x] Preloader
- [x] Read me
- [x] Active state for nav link
